Add remove
AbdelazizSoliman/Todo-List pull request #2
Opened 2023-03-02 01:16 UTC by AbdelazizSoliman

In this pull request:

- [ ] I created add and delete function.
- [ ] saved to local storage.

2023-03-02 01:49 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @AbdelazizSoliman, 
I'm Andres.

While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

- [ ] 🚧 According to the requirements, the edit task feature should be implemented:

![image](https://user-images.githubusercontent.com/77069011/222309868-921453dd-1892-4c5d-95fd-a6f1c9308c81.png)

Please consider doing so! 🤓 🔧 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 01:49 UTC, anagudelogu commented on src/index.js
> +/*eslint-disable*/
- [ ] Please avoid disabling linter rules as they ensure you follow a consistent code format and also apply best practices, instead consider fixing the errors! 🤓 🔧

2023-03-02 01:49 UTC, anagudelogu commented on src/index.js
> +    /*eslint-disable*/
- [ ] Please avoid disabling linter rules as they ensure you follow a consistent code format and also apply best practices, instead consider fixing the errors! 🤓 🔧

2023-03-02 01:49 UTC, anagudelogu commented on src/index.js
> +    /*eslint-disable*/
- [ ] Please avoid disabling linter rules as they ensure you follow a consistent code format and also apply best practices, instead consider fixing the errors! 🤓 🔧

2023-03-02 01:49 UTC, anagudelogu commented on src/index.js
> +};
- [ ] According to the requirements:
![image](https://user-images.githubusercontent.com/77069011/222309458-83108e27-828a-498a-bc8e-9c17910b09d4.png)

This new functionality should be in a new, separate file, please consider applying it! 🤓

2023-03-02 01:49 UTC, anagudelogu commented on src/index.js
> +}
- [ ] Also, according to the requirements: 

![image](https://user-images.githubusercontent.com/77069011/222309573-0696fec8-8f55-48a8-b33b-354cee4c24b7.png)

Indexes should get updated upon deleting a task, but you haven't implemented that feature yet, please consider doing it! 🤓 🔧

2023-03-04 15:41 UTC, Shedrack-Sunday approved these changes
Hi @AbdelazizSoliman 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


# Highlights
- No linter errors ✔️
- Good implementations ✔️


## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

__check the comments for details

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-06 09:57 UTC, merged